project:
  type: website
  title: "Nicoletta & Burc"
  output-dir: _site

website:
  title: ""
  site-url: https://lanholeto.github.io/nbwedding/
  back-to-top-navigation: true
  page-navigation: true
  search: false

  navbar:
    search: true
    background: "#f4f1ec"
    left:
      - href: index.qmd
        text: Home
      - href: content/our-story.qmd
        text: Our story
      - href: content/schedule.qmd
        text: Wedding Schedule
      - href: content/travel.qmd
        text: Travel
      - href: content/rsvp.qmd
        text: RSVP
        
  page-footer:
    center: |
      © 2026 &middot; Made with {{< bi heart-fill >}} and 
      [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/) by Luis Anholeto
format:
  html:
    theme:
      - _styles/wedding-theme-v2.scss
    toc: false
    page-layout: full
    link-external-newwindow: true
    smooth-scroll: true

execute:
  freeze: auto