project:
  type: website
  output-dir: _site

website:
  title: ""
  site-url: https://lanholeto.github.io/nbwedding/
  back-to-top-navigation: true
  page-navigation: true
  search: true

  navbar:
    search: true
    background: "#f4f1ec"
    left:
      - href: index.qmd
        text: Home
      - href: content/our-story.qmd
        text: Our story
      - href: content/schedule.qmd
        text: Schedule
      - href: content/travel.qmd
        text: Travel
      - href: content/rsvp.qmd
        text: RSVP

format:
  html:
    theme:
      - _styles/wedding-theme-v2.scss
    toc: false
    page-layout: full
    link-external-newwindow: true
    smooth-scroll: true

execute:
  freeze: auto